<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array/>
	<key>foldingStartMarker</key>
	<string>/\*\*</string>
	<key>foldingStopMarker</key>
	<string>\*\*/</string>
	<key>name</key>
	<string>js++Doc</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>(/\*\*)\s*$</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.begin.jsppDoc</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\*/</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.jsppDoc</string>
				</dict>
			</dict>
			<key>name</key>
			<string>comment.block.documentation.jsppDoc</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#invalid</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\*\s*(?=\w)</string>
					<key>contentName</key>
					<string>text.html</string>
					<key>end</key>
					<string>(?=\s*\*\s*@)|(?=\s*\*\s*/)</string>
					<key>name</key>
					<string>meta.documentation.comment.jsppDoc</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#inline</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\*\s*((\@)param)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.documentation.param.jsppDoc</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.keyword.jsppDoc</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>text.html</string>
					<key>end</key>
					<string>(?=\s*\*\s*@)|(?=\s*\*\s*/)</string>
					<key>name</key>
					<string>meta.documentation.tag.param.jsppDoc</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#inline</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\*\s*((\@)return)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.documentation.return.jsppDoc</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.keyword.jsppDoc</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>text.html</string>
					<key>end</key>
					<string>(?=\s*\*\s*@)|(?=\s*\*\s*/)</string>
					<key>name</key>
					<string>meta.documentation.tag.return.jsppDoc</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#inline</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\*\s*(\{{.*\}})</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.documentation.return.jsppDoc</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.keyword.jsppDoc</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>text.html</string>
					<key>end</key>
					<string>\*</string>
					<key>name</key>
					<string>comment.block.jspp</string>
					
	
				</dict>
				<dict>
					<key>begin</key>
					<string>\*\s*((\@)throws)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.documentation.throws.jsppDoc</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.keyword.jsppDoc</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>text.html</string>
					<key>end</key>
					<string>(?=\s*\*\s*@)|(?=\s*\*\s*/)</string>
					<key>name</key>
					<string>meta.documentation.tag.throws.jsppDoc</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#inline</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\*\s*((\@)exception)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.documentation.exception.jsppDoc</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.keyword.jsppDoc</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>text.html</string>
					<key>end</key>
					<string>(?=\s*\*\s*@)|(?=\s*\*\s*/)</string>
					<key>name</key>
					<string>meta.documentation.tag.exception.jsppDoc</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#inline</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\*\s*((\@)author)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.documentation.author.jsppDoc</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.keyword.jsppDoc</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>text.html</string>
					<key>end</key>
					<string>(?=\s*\*\s*@)|(?=\s*\*\s*/)</string>
					<key>name</key>
					<string>meta.documentation.tag.author.jsppDoc</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#inline</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\*\s*((\@)version)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.documentation.version.jsppDoc</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.keyword.jsppDoc</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>text.html</string>
					<key>end</key>
					<string>(?=\s*\*\s*@)|(?=\s*\*\s*/)</string>
					<key>name</key>
					<string>meta.documentation.tag.version.jsppDoc</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#inline</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\*\s*((\@)see)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.documentation.see.jsppDoc</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.keyword.jsppDoc</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>text.html</string>
					<key>end</key>
					<string>(?=\s*\*\s*@)|(?=\s*\*\s*/)</string>
					<key>name</key>
					<string>meta.documentation.tag.see.jsppDoc</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#inline</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\*\s*((\@)since)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.documentation.since.jsppDoc</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.keyword.jsppDoc</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>text.html</string>
					<key>end</key>
					<string>(?=\s*\*\s*@)|(?=\s*\*\s*/)</string>
					<key>name</key>
					<string>meta.documentation.tag.since.jsppDoc</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#inline</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\*\s*((\@)serial)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.documentation.serial.jsppDoc</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.keyword.jsppDoc</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>text.html</string>
					<key>end</key>
					<string>(?=\s*\*\s*@)|(?=\s*\*\s*/)</string>
					<key>name</key>
					<string>meta.documentation.tag.serial.jsppDoc</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#inline</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\*\s*((\@)serialField)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.documentation.serialField.jsppDoc</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.keyword.jsppDoc</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>text.html</string>
					<key>end</key>
					<string>(?=\s*\*\s*@)|(?=\s*\*\s*/)</string>
					<key>name</key>
					<string>meta.documentation.tag.serialField.jsppDoc</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#inline</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\*\s*((\@)serialData)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.documentation.serialData.jsppDoc</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.keyword.jsppDoc</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>text.html</string>
					<key>end</key>
					<string>(?=\s*\*\s*@)|(?=\s*\*\s*/)</string>
					<key>name</key>
					<string>meta.documentation.tag.serialData.jsppDoc</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#inline</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\*\s*((\@)deprecated)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.documentation.deprecated.jsppDoc</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.keyword.jsppDoc</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>text.html</string>
					<key>end</key>
					<string>(?=\s*\*\s*@)|(?=\s*\*\s*/)</string>
					<key>name</key>
					<string>meta.documentation.tag.deprecated.jsppDoc</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#inline</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.documentation.custom.jsppDoc</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.keyword.jsppDoc</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\*\s*((\@)\S+)\s</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>inline</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#invalid</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#inline-formatting</string>
				</dict>
				<dict>
					<key>include</key>
					<string>text.html.basic</string>
				</dict>
				<dict>
					<key>match</key>
					<string>((https?|s?ftp|ftps|file|smb|afp|nfs|(x-)?man|gopher|txmt)://|mailto:)[-:@a-zA-Z0-9_.~%+/?=&amp;#]+(?&lt;![.?:])</string>
					<key>name</key>
					<string>markup.underline.link</string>
				</dict>
			</array>
		</dict>
		<key>inline-formatting</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(\{)((\@)code)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.directive.begin.jsppDoc</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.other.documentation.directive.code.jsppDoc</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.keyword.jsppDoc</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>markup.raw.code.jsppDoc</string>
					<key>end</key>
					<string>\}</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.directive.end.jsppDoc</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.directive.code.jsppDoc</string>
					<key>patterns</key>
					<array/>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\{)((\@)literal)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.directive.begin.jsppDoc</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.other.documentation.directive.literal.jsppDoc</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.keyword.jsppDoc</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>markup.raw.literal.jsppDoc</string>
					<key>end</key>
					<string>\}</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.directive.end.jsppDoc</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.directive.literal.jsppDoc</string>
					<key>patterns</key>
					<array/>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.directive.begin.jsppDoc</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.other.documentation.directive.docRoot.jsppDoc</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.keyword.jsppDoc</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.directive.end.jsppDoc</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\{)((\@)docRoot)(\})</string>
					<key>name</key>
					<string>meta.directive.docRoot.jsppDoc</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.directive.begin.jsppDoc</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.other.documentation.directive.inheritDoc.jsppDoc</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.keyword.jsppDoc</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.directive.end.jsppDoc</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\{)((\@)inheritDoc)(\})</string>
					<key>name</key>
					<string>meta.directive.inheritDoc.jsppDoc</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.directive.begin.jsppDoc</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.other.documentation.directive.link.jsppDoc</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.keyword.jsppDoc</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>markup.underline.link.jsppDoc</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>string.other.link.title.jsppDoc</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.directive.end.jsppDoc</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\{)((\@)link)(?:\s+(\S+?))?(?:\s+(.+?))?\s*(\})</string>
					<key>name</key>
					<string>meta.directive.link.jsppDoc</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.directive.begin.jsppDoc</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.other.documentation.directive.linkplain.jsppDoc</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.keyword.jsppDoc</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>markup.underline.linkplain.jsppDoc</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>string.other.link.title.jsppDoc</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.directive.end.jsppDoc</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\{)((\@)linkplain)(?:\s+(\S+?))?(?:\s+(.+?))?\s*(\})</string>
					<key>name</key>
					<string>meta.directive.linkplain.jsppDoc</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.directive.begin.jsppDoc</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.other.documentation.directive.value.jsppDoc</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.keyword.jsppDoc</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>variable.other.jsppDoc</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.directive.end.jsppDoc</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\{)((\@)value)\s*(\S+?)?\s*(\})</string>
					<key>name</key>
					<string>meta.directive.value.jsppDoc</string>
				</dict>
			</array>
		</dict>
		<key>invalid</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>^(?!\s*\*).*$\n?</string>
					<key>name</key>
					<string>invalid.illegal.missing-asterisk.jsppDoc</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.html.jsppDoc</string>
	<key>uuid</key>
	<string>64BB98A8-59D4-474E-9991-C1E1D04BDD03</string>
</dict>
</plist>
